### ISSUE TITLE
Error importing external jsonschema in  jsonschema2pojo-maven-plugin:1.0.2

### ISSUE THREAD

**Issue by andrevocat** [joelittlejohn/jsonschema2pojo#1119]
[ERROR] Failed to execute goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:1.0.2:generate (default) on project resource_json_schema: Execution default of goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:1.0.2:generate failed: Error parsing document: http://geojson.org/schema/Point.json: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
[ERROR]  at [Source: (URL); line: 1, column: 2]

**Comment by andrevocat** [comment]
here sample jsonschema:

{
  "$schema": "http://json-schema.org/draft-07/schema",
  "asciiDocTagDefinitions":{"$comment": " tag::definitions[] "},
  "definitions": {
  }
  ,"asciiDocEndDefinitions":{"$comment": " end::definitions[] "},
  "type": "object",
  "$id": "node",
  "properties": {
   "location": {
      "$ref": "http://geojson.org/schema/Point.json"
    }
  },
  "required": [
    "location"
  ],
  "additionalProperties": false
}

**Comment by andrevocat** [comment]
closed by accident sorry

**Comment by joelittlejohn** [comment]
Are you accessing the internet through a proxy or something? It looks like you're getting a document with a '<' character at the start, instead of the expected JSON. It's probably an HTML page.

**Comment by andrevocat** [comment]
no i dont connect via proxy, same machine with browser gives me proper json:
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://geojson.org/schema/Point.json",
  "title": "GeoJSON Point",
  "type": "object",
  "required": [
    "type",
    "coordinates"
  ],
  "properties": {
    "type": {
      "type": "string",
      "enum": [
        "Point"
      ]
    },
    "coordinates": {
      "type": "array",
      "minItems": 2,
      "items": {
        "type": "number"
      }
    },
    "bbox": {
      "type": "array",
      "minItems": 4,
      "items": {
        "type": "number"
      }
    }
  }
}

**Comment by andrevocat** [comment]
is there a way to swich on debug/trace information?

**Comment by andrevocat** [comment]
Setup with a small Test-Implementatio  based on:
https://github.com/joelittlejohn/jsonschema2pojo/wiki/Getting-Started#using-jsonschema2pojo-within-your-java-project-embedded

i get following stack-dump:

Exception in thread "main" java.lang.IllegalArgumentException: Error parsing document: http://geojson.org/schema/Point.json
	at org.jsonschema2pojo.ContentResolver.resolve(ContentResolver.java:78)
	at org.jsonschema2pojo.SchemaStore.create(SchemaStore.java:59)
	at org.jsonschema2pojo.SchemaStore.create(SchemaStore.java:132)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:69)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:38)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:70)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:40)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:70)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:38)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:115)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:64)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:80)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:35)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:85)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:76)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:38)
	at org.jsonschema2pojo.SchemaMapper.generate(SchemaMapper.java:92)
	at ch.intersys.TestGenerate.main(TestGenerate.java:73)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (URL); line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2655)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:857)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:754)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4247)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2769)
	at org.jsonschema2pojo.ContentResolver.resolve(ContentResolver.java:76)

**Comment by andrevocat** [comment]
Error is occuring in    JsonEncoding enc = detectEncoding(); in class ByteSourceJsonBootstrapper
so its in jackson library. 

i'm closing issue

**Comment by andrevocat** [comment]
additional information:  server is responing with 301 permantly moved to https ! chaning protocoll to https and it works`!
