### ISSUE TITLE
Support a property with name 'additionalProperties' in the schema

### ISSUE THREAD

**Issue by vipulj169** [joelittlejohn/jsonschema2pojo#1120]
Hi,
Firstly, I'd like to thank you for this wonderful library. 
We've been using it for a while. To handle synchronization issue (Generated POJOs reaching different systems over time), we wanted to start generating 'additionalProperties' map in all our generated POJOs. However, I was wondering what would happen if the schema itself had a property called 'additionalProperties'. The current implementation fails with the following error:
`
java.lang.IllegalArgumentException: trying to create the same field twice: additionalProperties
	at com.sun.codemodel.JDefinedClass.field(JDefinedClass.java:425)
	at com.sun.codemodel.JDefinedClass.field(JDefinedClass.java:396)
	at org.jsonschema2pojo.rules.AdditionalPropertiesRule.addAdditionalPropertiesField(AdditionalPropertiesRule.java:132)
	at org.jsonschema2pojo.rules.AdditionalPropertiesRule.apply(AdditionalPropertiesRule.java:108)
	at org.jsonschema2pojo.rules.AdditionalPropertiesRule.apply(AdditionalPropertiesRule.java:43)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:125)
	at com.amazon.skill.manifest.generator.CustomObjectRule.apply(CustomObjectRule.java:81)
	at com.amazon.skill.manifest.generator.CustomObjectRule.apply(CustomObjectRule.java:37)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:90)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:40)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
	at com.amazon.skill.manifest.generator.CustomSchemaRule.apply(CustomSchemaRule.java:59)
	at com.amazon.skill.manifest.generator.CustomSchemaRule.apply(CustomSchemaRule.java:42)
	at com.amazon.skill.manifest.generator.CustomSchemaRule.apply(CustomSchemaRule.java:17)
	at org.jsonschema2pojo.SchemaMapper.generate(SchemaMapper.java:92)
	at com.amazon.skill.manifest.generator.SkillManifestJavaLibraryGenerator.generateJavaFile(SkillManifestJavaLibraryGenerator.java:54)
	at com.amazon.skill.manifest.generator.SkillManifestJavaLibraryGeneratorTest.testGenerateJavaFileValidURL(SkillManifestJavaLibraryGeneratorTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:168)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
`

One way to overcome this was to copy AdditionalPropertiesRule and prepend with a special character (say underscore).
Have you thought about this problem? Is the above way recommended way to handle this or you have a better suggestion?

Sample schema used for testing
`
{
    "$schema":"http://test.json-schema.org/draft-04/schema#",
    "definitions":{
    },
    "id":"http://example.com/example.test.json",
    "properties":{
        "key":{
            "type":"string"
        },
        "additionalProperties": {
            "javaType": "java.util.Map",
            "properties": {
                "type": "object"
            },
            "type": "object"
        }
    },
    "type":"object"
}
`

**Comment by eirnym** [comment]
@vipulj169 thank you for an issue, 

1) `existingJavaType` should be used as generator won't create a class `java.util.Map`
2) example have a mistake, let me explain as how I read this scheme :

it defines an object which contains a property `key` with type of `string`. Any other property of this object (e.g. `value` or `red` or any other one) should be an object.

the problem with scheme is it has `"properties": { "type": "object" }` and I guess you meant `"additionalProperties": { "type": "object" }` to make sure that you define any possible key-value.

BTW,  `"properties": { "type": "object" }` is an error itself, as you specified property "type" with wrong definition.

**Comment by vipulj169** [comment]
You're right on the invalid schema. Thanks for pointing that out. 
Let me ask the problem using this simple schema:
`
{
  "$schema": "http://test.json-schema.org/draft-04/schema#",
  "definitions": {
  },
  "id": "http://example.com/example.test.json",
  "properties": {
    "key": {
      "type": "string"
    },
    "additionalProperties": {
      "type": "string"
    }
  }
}
`
I used this schema to generate POJO using this tool (http://www.jsonschema2pojo.org/), with `Allow additional properties` checkbox selected. This results in the following error: 
`There's a problem: trying to create the same field twice: additionalProperties`
I was wondering if there was to support a schema which has a property by the name of `additionalProperties` as well as support new/additional properties.

**Comment by eirnym** [comment]
I used jsonschema python package to test it, and it seems ok. (I often use cross language to make sure if implementation is correct.

Which parameters do you use to run a generator? 
I've got a following result with this schema:

```java
$ ~/Downloads/jsonschema2pojo-1.0.2/bin/jsonschema2pojo -s test.json -t xxx && cat xxx/Test.java
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "key",
    "additionalProperties"
})
public class Test {

    @JsonProperty("key")
    private String key;
    @JsonProperty("additionalProperties")
    private String additionalProperties;

    @JsonProperty("key")
    public String getKey() {
        return key;
    }

    @JsonProperty("key")
    public void setKey(String key) {
        this.key = key;
    }

    @JsonProperty("additionalProperties")
    public String getAdditionalProperties() {
        return additionalProperties;
    }

    @JsonProperty("additionalProperties")
    public void setAdditionalProperties(String additionalProperties) {
        this.additionalProperties = additionalProperties;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(Test.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("key");
        sb.append('=');
        sb.append(((this.key == null)?"<null>":this.key));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.key == null)? 0 :this.key.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof Test) == false) {
            return false;
        }
        Test rhs = ((Test) other);
        return (((this.key == rhs.key)||((this.key!= null)&&this.key.equals(rhs.key)))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))));
    }

}

```

**Comment by eirnym** [comment]
The generator is a bit wierd for additionalProperties, though.
If I enable them, I'll got the same exception:

```sh
$ ~/Downloads/jsonschema2pojo-1.0.2/bin/jsonschema2pojo -s test.json -t xxx -D
Exception in thread "main" java.lang.IllegalArgumentException: trying to create the same field twice: additionalProperties
	at com.sun.codemodel.JDefinedClass.field(JDefinedClass.java:425)
	at com.sun.codemodel.JDefinedClass.field(JDefinedClass.java:396)
	at org.jsonschema2pojo.rules.AdditionalPropertiesRule.addAdditionalPropertiesField(AdditionalPropertiesRule.java:137)
	at org.jsonschema2pojo.rules.AdditionalPropertiesRule.apply(AdditionalPropertiesRule.java:113)
	at org.jsonschema2pojo.rules.AdditionalPropertiesRule.apply(AdditionalPropertiesRule.java:48)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:121)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:64)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:80)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:35)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:85)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:76)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:38)
	at org.jsonschema2pojo.SchemaMapper.generate(SchemaMapper.java:92)
	at org.jsonschema2pojo.Jsonschema2Pojo.generate(Jsonschema2Pojo.java:79)
	at org.jsonschema2pojo.cli.Jsonschema2PojoCLI.main(Jsonschema2PojoCLI.java:57)
```

**Comment by eirnym** [comment]
@vipulj169 BTW, it's not a property with name `additionalProperties`, they're any other property you want to add, e.g.:

you need a `key` property with type `integer` and other properties like `value1`, `value2`', `abc` and any other combination with type `string`
it works like you put "propertyNames": {"^.*$": {"type": "integer"}}` instead of `additionalProperties`.

**Comment by eirnym** [comment]
@vipulj169 in your case it'd be easier to rename field in POJO (I assume you want the schema as it is), rather than rename `additionalProperties` when you need them

**Comment by vipulj169** [comment]
Thanks for your suggestion. However, in my case, the fields in POJO is determined externally. What I could control is the generated field: `additionalProperties`. For now, I've copied AdditionalPropertiesRule and updated the field name to `_additionalProperties`.

**Comment by eirnym** [comment]
in POJO or in schema? I bet in schema and do you really need to allow `additionalProperties` at all?
