### ISSUE TITLE
NoClassDefFoundError raised trying to generated constructor with superclass fields

### ISSUE THREAD

**Issue by twheys** [joelittlejohn/jsonschema2pojo#1179]
I'm running into an issue trying to generate a subclass POJO from an existing parent class with a constructor that includes its superclass fields.

Here's my code

**existing Parent Class**
```
package com.r9.example.client.common;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;

import java.io.Serializable;

@JsonPropertyOrder({
        "a",
        "b"
})
public class Parent implements Serializable {
    private static final long serialVersionUID = 1L;

    @JsonProperty("a")
    private String fieldA;
    @JsonProperty("b")
    private String fieldB;

    public Parent() {
    }

    public Parent(String fieldA, String fieldB) {
        this.fieldA = fieldA;
        this.fieldB = fieldB;
    }

    public String getFieldA() {
        return fieldA;
    }

    public void setFieldA(String fieldA) {
        this.fieldA = fieldA;
    }

    public String getFieldB() {
        return fieldB;
    }

    public void setFieldB(String fieldB) {
        this.fieldB = fieldB;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;

        if (o == null || getClass() != o.getClass()) return false;

        Parent parent = (Parent) o;

        return new EqualsBuilder()
                .append(fieldA, parent.fieldA)
                .append(fieldB, parent.fieldB)
                .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37)
                .append(fieldA)
                .append(fieldB)
                .toHashCode();
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this)
                .append("fieldA", fieldA)
                .append("fieldB", fieldB)
                .toString();
    }
}
```

**Schema**
```
{
  "type": "object",
  "javaType": "com.r9.example.client.api.Child",
  "properties": {
    "c": {
      "type": "string",
      "javaName": "fieldC"
    }
  },
  "extends": {
    "type": "object",
    "existingJavaType": "com.r9.example.client.common.Parent",
    "properties": {
      "a": {
        "type": "string",
        "javaName": "fieldA"
      },
      "b": {
        "type": "string",
        "javaName": "fieldB"
      }
    }
  },
  "required": [
    "a",
    "b",
    "c"
  ]
}
```

Generation via Java API
```
package com.r9.example;

import com.sun.codemodel.JCodeModel;
import org.jsonschema2pojo.*;
import org.jsonschema2pojo.rules.RuleFactory;

import java.net.URL;
import java.nio.file.Files;

/**
 * A Camel Application
 */
public class MainApp {

    /**
     * A main() so we can easily run these routing rules in our IDE
     */
    public static void main(String... args) throws Exception {
        JCodeModel codeModel = new JCodeModel();
        URL source = MainApp.class.getResource("/pojo.schema.json");
        GenerationConfig config = new DefaultGenerationConfig() {
            @Override
            public String getTargetPackage() {
                return "com.r9.whopper.client.api";
            }

            @Override
            public boolean isIncludeJsr303Annotations() {
                return true;
            }

            @Override
            public String getDateTimeType() {
                return "java.time.LocalDateTime";
            }

            @Override
            public String getDateType() {
                return "java.time.LocalDate";
            }

            @Override
            public String getTimeType() {
                return "java.time.LocalTime";
            }

            @Override
            public boolean isFormatDateTimes() {
                return true;
            }

            @Override
            public boolean isFormatDates() {
                return true;
            }

            @Override
            public boolean isFormatTimes() {
                return true;
            }

            @Override
            public boolean isUsePrimitives() {
                return true;
            }

            @Override
            public boolean isSerializable() {
                return true;
            }

            @Override
            public boolean isIncludeConstructors() {
                return true;
            }

            @Override
            public boolean isIncludeAllPropertiesConstructor() {
                return true;
            }

            @Override
            public boolean isIncludeAdditionalProperties() {
                return false;
            }

            @Override
            public boolean isIncludeToString() {
                return true;
            }

            @Override
            public boolean isIncludeHashcodeAndEquals() {
                return true;
            }
        };

        final RuleFactory ruleFactory = new RuleFactory(config, new Jackson2Annotator(config), new SchemaStore());
        final SchemaMapper mapper = new SchemaMapper(ruleFactory, new SchemaGenerator());

        mapper.generate(codeModel, "ClassName", "com.r9.example", source);

        codeModel.build(Files.createTempDirectory("src/generated").toFile());
    }

}
```

**And the associated pom.xml**
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <properties>
        <maven.compiler.target>1.11</maven.compiler.target>
        <maven.compiler.source>1.11</maven.compiler.source>
        <jackson.version>2.11.3</jackson.version>
    </properties>

    <groupId>com.r9.example</groupId>
    <artifactId>testjsonschema2pojo</artifactId>
    <version>1.0-SNAPSHOT</version>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>7</source>
                    <target>7</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jsonschema2pojo</groupId>
            <artifactId>jsonschema2pojo-core</artifactId>
            <version>1.0.2</version>
        </dependency>
    </dependencies>
</project>
```

Running this results in the following exception
```
Exception in thread "main" java.lang.NoClassDefFoundError: Parent
	at org.jsonschema2pojo.util.ReflectionHelper.lambda$_getClass$3(ReflectionHelper.java:134)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.jsonschema2pojo.util.ReflectionHelper._getClass(ReflectionHelper.java:134)
	at org.jsonschema2pojo.util.ReflectionHelper.definedClassOrNullFromType(ReflectionHelper.java:129)
	at org.jsonschema2pojo.util.ReflectionHelper.searchSuperClassesForField(ReflectionHelper.java:85)
	at org.jsonschema2pojo.rules.ConstructorRule.generateFieldsConstructor(ConstructorRule.java:354)
	at org.jsonschema2pojo.rules.ConstructorRule.addFieldsConstructor(ConstructorRule.java:142)
	at org.jsonschema2pojo.rules.ConstructorRule.handleMultiChoiceConstructorConfiguration(ConstructorRule.java:130)
	at org.jsonschema2pojo.rules.ConstructorRule.apply(ConstructorRule.java:62)
	at org.jsonschema2pojo.rules.ConstructorRule.apply(ConstructorRule.java:45)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:143)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:64)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:80)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:35)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:85)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:76)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:38)
	at org.jsonschema2pojo.SchemaMapper.generate(SchemaMapper.java:92)
	at com.r9.example.MainApp.main(MainApp.java:101)
```

I did some debugging and it looks like in `ReflectionHelper._getClass` the call to `_package.classes()` returns an empty array. It looks like JPackage does not initially load anything into its `classes` attribute unless the `_class` method is called, so calling `_package._class(fieldClass.name())`  in `definedClassOrNullFromType` returns the class that you're trying to get. Suppose it might be preferable to use the built in methods of codemodel rather than the custom methods in `ReflectionHelper` to get the superclass?

Could also be something is wrong with my schema, so any feedback would be appreciated. Thanks!

**Comment by unkish** [comment]
Hi

I believe that this is due to the fact that
> That extends value can be a schema given in-line, or referenced using `$ref`.

Please see [reference for extends](https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#extends)

**Comment by twheys** [comment]
Hi @unkish thanks for the feedback. Yeah, the docs don't really cover this feature well. The code does appear to handle what I am trying to do, just looks like it's a small bug in the way codemodel is used.

**Comment by unkish** [comment]
It seems that there might be a misunderstanding/miscommunication.
To be clear, what I was trying to say is that according to code/[integration tests](https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/ExtendsIT.java)/[reference documentation](https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#extends) `extends` was not meant to work with anything other than `$ref` or embedded schemas.

So in that sense provided schema is incorrect as it uses `existingJavaType`.

**Comment by twheys** [comment]
Ok - What I am trying to accomplish is to generate a POJO that extends and existing class with a constructor that includes the superclass fields. Do you know if that is currently possible to do?

**Comment by unkish** [comment]
First of all sorry for delayed response.

In my opinion one possible way to "reliably" achieve that would be creating of custom "extension" such that it would read all the super class constructor parameters which one would have to define/list in json schema.

To elaborate a bit on issues with different approaches:

1. I can't see how it could be done via codemodel itself since codemodel is code generator and not parser.
Existing java classes that are reachable end up being `JReferencedClass` those that are not end up being `JDirectClass`, neither of which provides required information about underlying/wrapped class.
2. Getting constructor parameter names from class file is only possible
2.1 through reflection in case class was explicitly compiled with `-parameters` option (available since JDK8).
2.2 from bytecode (ie. by using ASM) in case class was compiled with debug information.

This leaves few options:

1. Attempt to grab and parse source code (`*.java`) of super class which for various reasons might not always be possible
2. In case super class(es) are always compiled with either `-parameters` or debug information and are on classpath - use reflection/ASM to get required data and have 
3. Describe super values of superclass in schema
