### ISSUE TITLE
Checking the handling of curly brackets for JSON object properties

### ISSUE THREAD

**Issue by Markus-Elfring** [joelittlejohn/jsonschema2pojo#1420]
I am trying the current software release out also together with [a JSON schema](https://json-schema.org/understanding-json-schema/reference/object.html#properties "Description for the usage of JSON object properties") like the following.

Example:
```JSON
{
  "$schema": "http://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/schemas/Staffelstufe",
  "type": "object",
  "required": ["Grenze", "Wert"],
  "properties":
  {
    "Grenze":
    {
      "type": "integer",
      "description": "Anzahl des Produktes, ab wo etwas anders berechnet werden soll."
    },
    "Wert":
    {
      "type": "number",
      "description": "Prozentwert für die Staffel"
    },
  }
}
```

I am wondering about the provided error message.

```
Markus_Elfring@…:~/Downloads/Freeware/jsonschema2pojo-1.1.2/bin> sh jsonschema2pojo -s ~/Test/JSON/Schemas/Staffelstufe-reduced-Schema1.json -t ~/Bau/JSON/Schemas/Staffel
Exception in thread "main" java.lang.IllegalArgumentException: Error parsing document: file:/home/Markus_Elfring/Test/JSON/Schemas/Staffelstufe-reduced-Schema1.json
        at org.jsonschema2pojo.ContentResolver.resolve(ContentResolver.java:78)
        at org.jsonschema2pojo.SchemaStore.create(SchemaStore.java:61)
        at org.jsonschema2pojo.SchemaStore.create(SchemaStore.java:140)
        at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:69)
        at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:38)
        at org.jsonschema2pojo.SchemaMapper.generate(SchemaMapper.java:92)
        at org.jsonschema2pojo.Jsonschema2Pojo.generate(Jsonschema2Pojo.java:79)
        at org.jsonschema2pojo.cli.Jsonschema2PojoCLI.main(Jsonschema2PojoCLI.java:58)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('}' (code 125)): was expecting double-quote to start field name
 at [Source: (URL); line: 18, column: 4]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2337)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:710)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:635)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleOddName(UTF8StreamJsonParser.java:2054)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parseName(UTF8StreamJsonParser.java:1705)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextFieldName(UTF8StreamJsonParser.java:1043)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:269)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:277)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:16)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4635)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3091)
        at org.jsonschema2pojo.ContentResolver.resolve(ContentResolver.java:76)
        ... 7 more
```

:crystal_ball: How should the tool implementation be improved further?

**Comment by Markus-Elfring** [comment]
It seems that the following code was not tolerated.

```
    },
  }
}
```


The following code was accepted with the deletion of a questionable comma and some Java code was generated accordingly.

Example:
```JSON
{
  "$schema": "http://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/schemas/Staffelstufe",
  "type": "object",
  "required": ["Grenze", "Wert"],
  "properties":
  {
    "Grenze":
    {
      "type": "integer",
      "description": "Anzahl des Produktes, ab wo etwas anders berechnet werden soll."
    },
    "Wert":
    {
      "type": "number",
      "description": "Prozentwert für die Staffel"
    }
  }
}
```

**Comment by joelittlejohn** [comment]
If you have invalid JSON in your file you will get a JSON parse exception. It indicates the position of the error and the problem. We use Jackson up parse JSON contents so we rely on Jackson to give as meaningful an error as it can.

**Comment by Markus-Elfring** [comment]
:thought_balloon: I became curious if the support will evolve further also for the handling of trailing commas (within arrays and objects).

**Comment by joelittlejohn** [comment]
One solution here is to use YAML Schema source type instead. I think YAML supports trailing commas (and JSON is valid YAML).

JSON doesn't allow trailing commas.

**Comment by Markus-Elfring** [comment]
:thought_balloon: Does such a wording refer to any contradictory information?

Would you find any related information sources interesting also for further software evolution? :thinking:
Example:
[JSON for Humans](https://json5.org/ "JSON5 data interchange format")
