### ISSUE TITLE
Task 'generateJsonSchema2Pojo' fails after upgrading to Android Gradle Plugin 8.2.2 / Gradle 8.2

### ISSUE THREAD

**Issue by masranber** [joelittlejohn/jsonschema2pojo#1591]
### Issue
The plugin appears to be incompatible with newer versions the Android Gradle Plugin (8.0.0+ from what I can tell).

I'm using version 1.2.1 of the jsonschema2pojo plugin in an Android library. I'm currently in the process of upgrading the project from Android Gradle Plugin version 7.2.0 to 8.2.2, which also requires Gradle version >= 8.2.

After upgrading AGP and Gradle, building the project fails due to an exception in the `generateJsonSchema2Pojo` Gradle task:

```
Execution failed for task ':mylibrary:generateJsonSchema2PojoForDebug'.
> No such property: extension for class: com.android.build.gradle.LibraryPlugin

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':mylibrary:generateJsonSchema2PojoForDebug'. <30 internal lines>
Caused by: groovy.lang.MissingPropertyException: No such property: extension for class: com.android.build.gradle.LibraryPlugin
	at org.jsonschema2pojo.gradle.GenerateJsonSchemaAndroidTask.setTargetVersion(GenerateJsonSchemaAndroidTask.groovy:69)
	at org.jsonschema2pojo.gradle.GenerateJsonSchemaAndroidTask$setTargetVersion.callCurrent(Unknown Source)
        at org.jsonschema2pojo.gradle.GenerateJsonSchemaAndroidTask.generate(GenerateJsonSchemaAndroidTask.groovy:52) <118 internal lines>

BUILD FAILED in 2s
```

Here's the source code snippet where the exception is being thrown:

https://github.com/joelittlejohn/jsonschema2pojo/blob/72050f6b94d46d51d7c93c51e35383cdf5fc733f/jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/GenerateJsonSchemaAndroidTask.groovy#L63-L73

### Steps to reproduce
1) Create a new, empty Android library project.
2) In 'project structure' menu in Android Studio, set AGP version to 8.2.2 and Gradle version to 8.2.
3) Apply the jsonschema2pojo plugin to the project.
4) Include a dummy json schema in the project (just so the generateJsonSchema2Pojo task runs).
4) Sync Gradle with project files.
5) Build project.
6) Build will fail with the above exception.

### Potential solution

In newer versions of the Android Gradle Plugin `extension` is no longer a member of the class `com.android.build.gradle.LibraryPlugin`. The `com.android.build.gradle.LibraryExtension` instance can instead be accessed via the `android` property of `org.gradle.api.Project` that gets added by the AGP.

Therefore, the following line:
```
configuration.targetVersion = project.plugins.getPlugin("com.android.library").extension.compileOptions.sourceCompatibility
```
should be changed to:
```
configuration.targetVersion = project.property("android").compileOptions.sourceCompatibility
```
In my limited testing (basically just running the code directly in my build.gradle script) this appears to work in the latest AGP version as well as the version I was previously using (7.2.0).

I believe this issue also applies to Android apps (`com.android.application` projects). Since the `android` property returns the correct project extension instance for the current project type (`com.android.application` or `com.android.library`) the above code should also work for `com.android.application` projects.

The `setTargetVersion` method would then look like:
```groovy
void setTargetVersion(JsonSchemaExtension configuration) { 
   if (!configuration.targetVersion) { 
     if (project.hasProperty("android")) { 
       configuration.targetVersion = project.property("android").compileOptions.sourceCompatibility 
       logger.info 'Using android.compileOptions.sourceCompatibility as targetVersion for jsonschema2pojo: ' + configuration.targetVersion 
     }
   } 
 }
```

I'm not sure if this issue appears elsewhere in the source code.

**Comment by oscar-tu-lotero** [comment]
Hi, @masranber , 
Have your found any way to workaround this issue in existing projects in some way, while we wait for a fix?

**Comment by masranber** [comment]
@oscar-tu-lotero I haven't found a solution yet. The plugin is already in a separate module from the main application. Would you mind posting your project-level build.gradle and module-level build.gradle to see if I can replicate your fix?

**Comment by unkish** [comment]
Out of curiosity: does explicitly setting&providing `targetVersion` help (as that should prevent code from entering 'problematic' `if` block) ?

**Comment by sahityadubey** [comment]
I am also experiencing a similar issue. Can you please help me with possible solutions?

```
**org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':SchlageHome:generateJsonSchema2PojoForDebug'.**
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:130)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:128)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:116)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)


**Caused by: groovy.lang.MissingPropertyException: No such property: extension for class: com.android.build.gradle.AppPlugin
	at org.jsonschema2pojo.gradle.GenerateJsonSchemaAndroidTask.setTargetVersion(GenerateJsonSchemaAndroidTask.groovy:66)
	at org.jsonschema2pojo.gradle.GenerateJsonSchemaAndroidTask$setTargetVersion.callCurrent(Unknown Source)
	at org.jsonschema2pojo.gradle.GenerateJsonSchemaAndroidTask.generate(GenerateJsonSchemaAndroidTask.groovy:52)**
```

**Comment by wikes82** [comment]
I'm currently having this same issue with Gradle 8.4.2 is there any workaround or fix ?
This is the error I'm getting : 
```FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateJsonSchema2PojoForDebug'.
> No such property: extension for class: com.android.build.gradle.AppPlugin
```

**Comment by masranber** [comment]
@wikes82 Try @unkish's suggestion above as a workaround

All you need to do is override `targetVersion` in your app-level `build.gradle:`
```gradle
tasks.matching { it.name.startsWith("generateJsonSchema2Pojo") }.configureEach {
    jsonSchema2Pojo.targetVersion = android.compileOptions.sourceCompatibility // override just before the jsonschema2pojo task runs
}
```

Setting `targetVersion` directly in the `jsonSchema2Pojo` block doesn't work:
```gradle
jsonSchema2Pojo {
    targetVersion = android.compileOptions.sourceCompatibility // throws IllegalStateException: sourceCompatibility is not yet finalized
}
```
You _could_ hardcode a `JavaVersion`, but then you have to maintain the version in two spots.

**Comment by wikes82** [comment]
@masranber Thanks for the response, I ended up creating separate java-library module  and put the schema in there instead of the main Android module
