### ISSUE TITLE
$ref doesn't support local definitions

### ISSUE THREAD

**Issue by tylerprete** [joelittlejohn/jsonschema2pojo#321]
I have this file (saved as entityType.json):
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/entityType",
  "id": "resource:///json_schema/match/entityType.json#",
  "definitions": {
    "entityType": {
      "enum": [ "LEAD", "CONTACT", "ACCOUNT", "OPPORTUNITY", "ROW" ]
    }
  }
}
```
This is valid jsonschema, and a fairly common pattern, but jsonschema2pojo fails compiling this file, with the error below. I have a change that solved this for my use-cases, though I'm not sure it's entirely safe. I'll link to it (https://github.com/joelittlejohn/jsonschema2pojo/pull/322).

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.816 s
[INFO] Finished at: 2015-03-19T22:19:36-07:00
[INFO] Final Memory: 7M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:0.4.10:generate (default) on project schema: Execution default of goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:0.4.10:generate failed: Path not present: definitions -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:0.4.10:generate (default) on project schema: Execution default of goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:0.4.10:generate failed: Path not present: definitions
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:0.4.10:generate failed: Path not present: definitions
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.IllegalArgumentException: Path not present: definitions
	at org.jsonschema2pojo.FragmentResolver.resolve(FragmentResolver.java:54)
	at org.jsonschema2pojo.FragmentResolver.resolve(FragmentResolver.java:31)
	at org.jsonschema2pojo.SchemaStore.create(SchemaStore.java:50)
	at org.jsonschema2pojo.SchemaStore.create(SchemaStore.java:93)
	at org.jsonschema2pojo.rules.PropertyRule.resolveRefs(PropertyRule.java:130)
	at org.jsonschema2pojo.rules.PropertyRule.resolveRefs(PropertyRule.java:132)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:78)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:42)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:60)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:31)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:115)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:61)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:85)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:35)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:66)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
	at org.jsonschema2pojo.SchemaMapper.generate(SchemaMapper.java:88)
	at org.jsonschema2pojo.Jsonschema2Pojo.generateRecursive(Jsonschema2Pojo.java:112)
	at org.jsonschema2pojo.Jsonschema2Pojo.generateRecursive(Jsonschema2Pojo.java:114)
	at org.jsonschema2pojo.Jsonschema2Pojo.generate(Jsonschema2Pojo.java:70)
	at org.jsonschema2pojo.maven.Jsonschema2PojoMojo.execute(Jsonschema2PojoMojo.java:480)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by joelittlejohn** [comment]
I'm going to close this as I think the comments on #322 describe this more accurately. Referring to local definitions is supported.
