### ISSUE TITLE
No signature of method: java.net.URL.mkdir()

### ISSUE THREAD

**Issue by maksimlikharev** [joelittlejohn/jsonschema2pojo#373]
* What went wrong:
A problem occurred configuring root project 'json-pojo'.
> No signature of method: java.net.URL.mkdir() is applicable for argument types: () values: []
Possible solutions: wait(), wait(long), is(java.lang.Object), split(groovy.lang.Closure), wait(long,
 int), toURI()

this is java8, jsonschema2pojo-gradle-plugin:0.4.11

what might be wrong here.

**Comment by joelittlejohn** [comment]
This one is stopping me making a release at the moment. @ben-manes any idea what's happening here?

```
    java(org.jsonschema2pojo.gradle.JsonSchemaPluginSpec)  Time elapsed: 16.64 sec  <<< ERROR!
    org.gradle.tooling.BuildException: Could not execute build using Gradle distribution 'http://services.gradle.org/distributions/gradle-2.3-bin.zip'.
    	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:55)
    	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConnection$2.run(DefaultAsyncConnection.java:71)
    	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:66)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    	at java.lang.Thread.run(Thread.java:745)
    	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
    	at org.gradle.tooling.internal.consumer.DefaultBuildLauncher.run(DefaultBuildLauncher.java:100)
    	at org.gradle.tooling.BuildLauncher$run.call(Unknown Source)
    	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    	at org.jsonschema2pojo.gradle.JsonSchemaPluginSpec.build(JsonSchemaPluginSpec.groovy:37)
    	at org.jsonschema2pojo.gradle.JsonSchemaPluginSpec.java(JsonSchemaPluginSpec.groovy:27)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:606)
    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:59)
    	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:120)
    	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:103)
    	at org.apache.maven.surefire.Surefire.run(Surefire.java:169)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:606)
    	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
    	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
    Caused by: org.gradle.internal.exceptions.LocationAwareException: A problem occurred configuring root project 'gradle-jsonschema2pojo-example'.
    	at org.gradle.initialization.DefaultExceptionAnalyser.transform(DefaultExceptionAnalyser.java:77)
    	at org.gradle.initialization.MultipleBuildFailuresExceptionAnalyser.transform(MultipleBuildFailuresExceptionAnalyser.java:47)
    	at org.gradle.initialization.StackTraceSanitizingExceptionAnalyser.transform(StackTraceSanitizingExceptionAnalyser.java:30)
    	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:108)
    	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
    	at org.gradle.tooling.internal.provider.BuildModelAction.run(BuildModelAction.java:43)
    	at org.gradle.tooling.internal.provider.BuildModelAction.run(BuildModelAction.java:30)
    	at org.gradle.tooling.internal.provider.ConfiguringBuildAction.run(ConfiguringBuildAction.java:119)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
    	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:48)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
    	at org.gradle.util.Swapper.swap(Swapper.java:38)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
    	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
    	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    Caused by: org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'gradle-jsonschema2pojo-example'.
    	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:91)
    	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:86)
    	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:65)
    	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:492)
    	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:86)
    	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
    	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
    	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
    	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
    	... 34 more
    Caused by: groovy.lang.MissingMethodException: No signature of method: java.net.URL.mkdir() is applicable for argument types: () values: []
    Possible solutions: wait(), wait(long), is(java.lang.Object), split(groovy.lang.Closure), wait(long, int), toURI()
    	at org.jsonschema2pojo.gradle.GenerateJsonSchemaTask$_configureJava_closure3.doCall(GenerateJsonSchemaTask.groovy:60)
    	at org.jsonschema2pojo.gradle.GenerateJsonSchemaTask.configureJava(GenerateJsonSchemaTask.groovy:60)
    	at org.jsonschema2pojo.gradle.GenerateJsonSchemaTask$_closure2.doCall(GenerateJsonSchemaTask.groovy:43)
    	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
    	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
    	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
    	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
    	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    	at com.sun.proxy.$Proxy10.afterEvaluate(Unknown Source)
    	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:79)
    	... 41 more
```

**Comment by ben-manes** [comment]
Is that an old stacktrace? `GenerateJsonSchemaTask#60` is the wrong line when comparing on master. If old, then this should be fixed in 81adfe7 where this happened in my build due to GenerationConfig's source being changing from File to URL.

**Comment by ben-manes** [comment]
My workaround for 0.4.11 was to explicitly set the `source` to the default value in my build script,

```gradle
source = files("${sourceSets.main.output.resourcesDir}/json")
```

This works because `mkdirs()` is called when the source is not configured and it ensures that the default directory exists for js2p to look in. Most likely when I wrote the plugin, if the folder didn't exist the generator fails. I don't know if that's is / still true.

It wouldn't hurt to transition over to typed Groovy so that refactorings don't break at runtime. But more importantly would be to add tests, which that commit made possible.

**Comment by maksimlikharev** [comment]
yes, setting path works, thanks

**Comment by joelittlejohn** [comment]
Thanks for looking Ben. I'm a little confused, as the Travis build is passing but when I run `mvn clean verify` on the current master I see that java(org.jsonschema2pojo.gradle.JsonSchemaPluginSpec) fails with the stacktrace I dumped above.

```
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T21:58:10+01:00)
Maven home: /usr/local/Cellar/maven/3.2.3/libexec
Java version: 1.7.0_71, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.2", arch: "x86_64", family: "mac"
```

**Comment by ben-manes** [comment]
It passes locally for me. Can you delete your `.m2/repository` (just this project is fine). In the commit I wrote,

>Note that due to the above mentioned bug, the CI may break as the
SNAPSHOT dependency won't be in the local repository, so the plugin
test will break by using an old plugin version. An `mvn install -DskipTests`
followed by a build shows the test passing.

This didn't break Travis because the m2 repository isn't being cached, whereas locally an old snapshot might be picked up.

**Comment by joelittlejohn** [comment]
My first thought was some bad cached content so I deleted `~/.m2/repository/org/jsonschema2pojo` but this didn't seem to make any difference. After `mvn install -DskipTests` I'm back in business, thanks!

It's not clear to me where the out-of-date snapshot was coming from (after clearing the local repo) - would it have been using the previous release? or do you think there's a bad snapshot published somewhere?

**Comment by joelittlejohn** [comment]
Oh and apologies for not looking back at the advice you pasted above. I saw you remind someone else about this not too long ago so I really should have remembered :)

**Comment by ben-manes** [comment]
No problem. I'm not sure why it finds the wrong version, and figured it was
was a stale local snapshot. Since it works with a clean m2 it must be a
local problem due to a stale build. Thankfully it's a one time fix.
