### ISSUE TITLE
Default type ordering

### ISSUE THREAD

**Issue by devldevelopment** [joelittlejohn/jsonschema2pojo#573]
Whenever I try and parse a default with multiple types, if "number" is before "String" and if the default is "auto" then there is an exception. E.g.

`{"type":["number","string"],"descriptionA":"ABC","descriptionEN":"the width","default":"auto"}`

It tries to parse the item as a number and I get:

`Exception in thread "main" java.lang.NumberFormatException: For input string: "auto"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at org.jsonschema2pojo.rules.DefaultRule.getDefaultValue(DefaultRule.java:116)
	at org.jsonschema2pojo.rules.DefaultRule.apply(DefaultRule.java:97)
	at org.jsonschema2pojo.rules.DefaultRule.apply(DefaultRule.java:51)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:103)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:43)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:64)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:32)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:127)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:72)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:89)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:39)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:75)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:43)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:64)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:32)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:127)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:72)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:89)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:39)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:66)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:75)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:43)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:64)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:32)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:127)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:72)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:89)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:39)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:66)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:66)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
	at org.jsonschema2pojo.SchemaMapper.generate(SchemaMapper.java:88)
	at org.jsonschema2pojo.Jsonschema2Pojo.generate(Jsonschema2Pojo.java:75)
	at org.jsonschema2pojo.cli.Jsonschema2PojoCLI.main(Jsonschema2PojoCLI.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)`

but it works is the types are `{"type":["string","number"] does this mean that multiple types are not supported for default and other properties, or is it a bug?

**Comment by joelittlejohn** [comment]
Yes, I'm afraid this library does not support union types, it just uses the first type that's present.
