### ISSUE TITLE
Object name of "_" causes exception

### ISSUE THREAD

**Issue by Smitty010** [joelittlejohn/jsonschema2pojo#632]
I have some json I'm trying to process that uses the single character "_" as the name (not the value) of one of the fields in the json.  If I had the option of changing the name of the field I would.  But, it's a third party library (apache solr).  At any rate, the normalizeName() function throws an exception.

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.charAt(Unknown Source)
        at org.jsonschema2pojo.util.NameHelper.normalizeName(NameHelper.java:45)

        at org.jsonschema2pojo.util.NameHelper.getPropertyName(NameHelper.java:76)

**Comment by joelittlejohn** [comment]
I guess we can fix this quite easily. Do you have any thoughts about what you'd _like_ to see generated when we encounter a property called `_`?

**Comment by Smitty010** [comment]
First, to be clear, I won't tell you I'm very animated about getting this fixed.  I'm ok if you ignore it or wait and fix it when there are other more important fixes.  

The workaround is straight forward.  Change the "_" in the example json to something like "underscore", generate the POJOs, and then go fix the annotations for this field.  Not that hard.  I've already done that.

Second, if it had been almost anyone else other than someone big like apache solr generating this, I wouldn't have said anything.  People who use names like this or (my bigger pet peave) use object names to provide some of the information about the object (like use the name of a server as the name of an object instead of having a string named "server" in the object with the name of the server as a value) are IMHO misusing the standard.  It makes parsing much harder as you either have to write a custom deserializer or use a map and lose the safety of having a real pojo with types for the values and a list of getters/setters.  OK, I feel better now.

If you do want to do something, I'd probably have the name of the field as "underscore" or "hyphen" if the name is "-".  But, again, I'm ok if you don't fix it.

Finally, I wanted to say this.  I have to generate parsers for some company's json on a regular basis.  Being able to take their example json (nobody gives me schemas), run it through your code and generate pojos has saved me a lot of time.  So, thank you for doing this program.

**Comment by joelittlejohn** [comment]
Thanks @Smitty010, it's nice to get this kind of insight into how you're thinking about this change.

I think if the string contains no valid characters we should use the unicode name for the chars within it. This could produce a long name, but it's an edge-case so as long as we have _some_ way to support this I think that's okay. We can prefix field name with something to indicate that it's a special translation (e.g. with `__` or `$`).

In this case, your underscore  field would have been translated to a field called:

`__low_line`

**Comment by joelittlejohn** [comment]
This kind of JSON:

```json
{
  "#!" : "foo",
  ";;" : "bar"
}
```

would produce fields named:

```
__number_sign_exclamation_mark
__semicolon_semicolon
```

**Comment by JohnLuCN** [comment]
I encountered the same exception, and finally found that the error is caused by **field name** which is using **Chinese Characters**....After changing to PinYin or English characters, exception will be eliminated.
Hope there could be some upgrade for such kind of situation:))

**Comment by firsovroman** [comment]
Faced the same exception when using Russian characters as keys. If I use English characters the problem goes away.
