### ISSUE TITLE
NPE when enabling includeDynamicAccessors

### ISSUE THREAD

**Issue by ben-manes** [joelittlejohn/jsonschema2pojo#666]
I was curious to see what the `includeDynamicAccessors` flag outputted. When I added it the task failed with,

```
Caused by: java.lang.NullPointerException
        at com.sun.codemodel.JInvocation.generate(JInvocation.java:176)
        at com.sun.codemodel.JFormatter.g(JFormatter.java:350)
        at com.sun.codemodel.JInvocation.state(JInvocation.java:198)
        at com.sun.codemodel.JFormatter.s(JFormatter.java:386)
        at com.sun.codemodel.JBlock.generateBody(JBlock.java:448)
        at com.sun.codemodel.JBlock.generate(JBlock.java:436)
        at com.sun.codemodel.JFormatter.g(JFormatter.java:350)
        at com.sun.codemodel.JConditional.state(JConditional.java:115)
        at com.sun.codemodel.JFormatter.s(JFormatter.java:386)
        at com.sun.codemodel.JBlock.generateBody(JBlock.java:448)
        at com.sun.codemodel.JBlock.generate(JBlock.java:436)
        at com.sun.codemodel.JFormatter.g(JFormatter.java:350)
        at com.sun.codemodel.JConditional.state(JConditional.java:115)
        at com.sun.codemodel.JFormatter.s(JFormatter.java:386)
        at com.sun.codemodel.JBlock.generateBody(JBlock.java:448)
        at com.sun.codemodel.JBlock.generate(JBlock.java:436)
        at com.sun.codemodel.JFormatter.g(JFormatter.java:350)
        at com.sun.codemodel.JConditional.state(JConditional.java:117)
        at com.sun.codemodel.JFormatter.s(JFormatter.java:386)
        at com.sun.codemodel.JBlock.generateBody(JBlock.java:448)
        at com.sun.codemodel.JBlock.generate(JBlock.java:436)
        at com.sun.codemodel.JFormatter.g(JFormatter.java:350)
        at com.sun.codemodel.JConditional.state(JConditional.java:117)
        at com.sun.codemodel.JFormatter.s(JFormatter.java:386)
        at com.sun.codemodel.JBlock.generateBody(JBlock.java:448)
        at com.sun.codemodel.JBlock.generate(JBlock.java:436)
        at com.sun.codemodel.JFormatter.g(JFormatter.java:350)
        at com.sun.codemodel.JConditional.state(JConditional.java:117)
        at com.sun.codemodel.JFormatter.s(JFormatter.java:386)
        at com.sun.codemodel.JBlock.generateBody(JBlock.java:448)
        at com.sun.codemodel.JBlock.generate(JBlock.java:436)
        at com.sun.codemodel.JFormatter.g(JFormatter.java:350)
        at com.sun.codemodel.JBlock.state(JBlock.java:464)
        at com.sun.codemodel.JFormatter.s(JFormatter.java:386)
        at com.sun.codemodel.JMethod.declare(JMethod.java:460)
        at com.sun.codemodel.JFormatter.d(JFormatter.java:376)
        at com.sun.codemodel.JDefinedClass.declareBody(JDefinedClass.java:815)
        at com.sun.codemodel.JDefinedClass.declare(JDefinedClass.java:788)
        at com.sun.codemodel.JFormatter.d(JFormatter.java:376)
        at com.sun.codemodel.JFormatter.write(JFormatter.java:406)
        at com.sun.codemodel.JPackage.build(JPackage.java:438)
        at com.sun.codemodel.JCodeModel.build(JCodeModel.java:311)
        at org.jsonschema2pojo.Jsonschema2Pojo.generate(Jsonschema2Pojo.java:82)
        at org.jsonschema2pojo.Jsonschema2Pojo$generate.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.jsonschema2pojo.gradle.GenerateJsonSchemaJavaTask.generate(GenerateJsonSchemaJavaTask.groovy:65)
```

**Comment by joelittlejohn** [comment]
@ben-manes do you have a simple schema that produces the problem?

**Comment by ben-manes** [comment]
Unfortunately I don't. This ran on a few dozen schemas, which have dependencies on each other. Taking it a few random ones and running it on the web tool doesn't fail. So I'm not sure how to provide a meaningful error.

**Comment by joelittlejohn** [comment]
Okay, no problem. It may be possible to simply understand this one using the code and your stack trace. @ctrimble might have some ideas here.

**Comment by ctrimble** [comment]
Thanks @ben-manes for report this.  I will see if I can put together a test case to reproduce it.

**Comment by ctrimble** [comment]
I am having a hard time creating a test that makes this fail.  @ben-manes to you have any other configuration options set?

**Comment by ben-manes** [comment]
Sorry that I can't be more descriptive. There's nothing confidential about the schemas, so I can probably wrap them into a project for you and email it across.

```gradle
jsonSchema2Pojo {
  removeOldOutput = false
  useCommonsLang3 = true
  generateBuilders = true
  includeConstructors = true
  includeJsr303Annotations = true
  propertyWordDelimiters = ['_'] as char[]
  targetPackage = '....'
  source = files("${sourceSets.main.output.resourcesDir}/json")
}
```

**Comment by ctrimble** [comment]
The schemas would be very helpful.

**Comment by ben-manes** [comment]
Sent to your gmail. Thanks!

**Comment by ctrimble** [comment]
So, dumped all of your schemas into a test, with your configuration, and I can get the generated output to compile.  Could this be due to `removeOldOutput = false`?

**Comment by ben-manes** [comment]
Changing that flag doesn't fix it locally. You ran it using the gradle build file? That should be reproducible unless there's a surprising environmental problem.

**Comment by ctrimble** [comment]
I dumped it into an IT test in maven to start.  I will see what Gradle is producing.

**Comment by ctrimble** [comment]
I can recreate it, so this should be enough info.

**Comment by ben-manes** [comment]
I just ran into this again and was about to report it anew. :)

I also noticed that the feature doesn't take effect unless I enable `includeDynamicAccessors` and either `includeDynamicGetters` or `includeDynamicSetters`. The description isn't clear that this has to be enabled as a gate before a subsetting is evaluated, which might be more clearly worded.

**Comment by ctrimble** [comment]
@ben-manes I am sorry this issue was never resolved.  I will see if I can dig up any work I did and throw together a PR with the schemas and test procedures to recreate the issue.

**Comment by ben-manes** [comment]
Oh it’s not a big deal. I will happily map by hand and that’s probably
better, since I rarely need this. Just amused since I completely forgot I
hit it before.

**Comment by ctrimble** [comment]
It looks like I don't have the tests mentioned in this issue.

**Comment by ben-manes** [comment]
Resent the original attachment, which was a failing Gradle build. I hope that helps, but you can also ignore this again as it is not blocking me.

**Comment by mrkarthik** [comment]
@ctrimble @joelittlejohn I am also seeing the same error, able to reproduce it with this schema.  I am using the maven plugin to generate the POJOs

**Schema:**
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "definitions": {
    "myObj": {
      "type": "object",
      "properties": {
        "foo": {
          "type": "string"
        },
        "bar": {
          "type": "integer"
        },
        "baz": {
          "type": "boolean"
        }
      }
    }
  },
  "properties": {
    "test": {
      "$ref": "#/definitions/myObj"
    }
  }
}
```

**Maven Plugin:**
```
<plugin>
    <groupId>org.jsonschema2pojo</groupId>
    <artifactId>jsonschema2pojo-maven-plugin</artifactId>
    <version>1.0.2</version>
    <executions>
        <execution>
            <configuration>
                <annotationStyle>jackson2</annotationStyle>
                <generateBuilders>true</generateBuilders>
                <includeAdditionalProperties>true</includeAdditionalProperties>
                <includeConstructors>false</includeConstructors>
                <includeDynamicAccessors>true</includeDynamicAccessors>
                <includeDynamicGetters>true</includeDynamicGetters>
                <includeGetters>true</includeGetters>
                <includeHashcodeAndEquals>true</includeHashcodeAndEquals>
                <includeJsr303Annotations>true</includeJsr303Annotations>
                <includeJsr305Annotations>true</includeJsr305Annotations>
                <includeSetters>false</includeSetters>
                <includeToString>true</includeToString>
                <inclusionLevel>NON_NULL</inclusionLevel>
                <initializeCollections>false</initializeCollections>
                <useInnerClassBuilders>true</useInnerClassBuilders>
            </configuration>
            <goals>
                <goal>generate</goal>
            </goals>
            <phase>generate-sources</phase>
        </execution>
    </executions>
</plugin>
```
