### ISSUE TITLE
Dealing with camelCase and underscores within the same JSON schema

### ISSUE THREAD

**Issue by james-woods** [joelittlejohn/jsonschema2pojo#811]
I have the following JSON schema, which is generated by scanning a MongoDB collection.
My goal is to generate POJOs from it to read the JSON dump-files generated through mongoexport:

```javascript
{
	"type": "object",
	"properties": {
		"userId": {
			"type": "string"
		},
		"timestamp": {
			"type": "string"
		},
		"contextAdCampaign": {
			"type": "object",
			"properties": {
				"customerName": {
					"type": "string"
				},
				"imageAssetId": {
					"type": "string"
				},
				"imageAssetUrl": {
					"type": "string"
				},
				"createdDate": {
					"type": "string"
				},
				"image_asset_id": {
					"type": "string"
				},
				"image_asset_url": {
					"type": "string"
				}
			},
			"required": ["createdDate"]
		}
	},
	"required": ["timestamp"]
}
```
My issue is that this schema causes an 
```
Exception in thread "main" java.lang.IllegalArgumentException: trying to create the same field twice: imageAssetId
```
when using jsonschema2pojo CLI and I don't know how to work around this. Is this a bug or am I missing a configuration feature of jsonschema2pojo?

Command used: `jsonschema2pojo -a JACKSON2 -bi -da -c -c3 -tv 1.8 -ds -p ch.project.update -sl -t ~/some/folder/ -s schema.json`

Full Stack trace:
```
Exception in thread "main" java.lang.IllegalArgumentException: trying to create the same field twice: imageAssetId
        at com.sun.codemodel.JDefinedClass.field(JDefinedClass.java:425)
        at com.sun.codemodel.JDefinedClass.field(JDefinedClass.java:396)
        at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:84)
        at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:43)
        at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:70)
        at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:38)
        at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:119)
        at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:70)
        at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:90)
        at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:40)
        at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
        at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
        at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:75)
        at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:43)
        at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:70)
        at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:38)
        at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:119)
        at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:70)
        at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:90)
        at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:40)
        at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
        at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:66)
        at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
        at org.jsonschema2pojo.SchemaMapper.generate(SchemaMapper.java:92)
        at org.jsonschema2pojo.Jsonschema2Pojo.generate(Jsonschema2Pojo.java:77)
        at org.jsonschema2pojo.cli.Jsonschema2PojoCLI.main(Jsonschema2PojoCLI.java:48)
```

**Comment by joelittlejohn** [comment]
Hi. The problem here is that by default, underscore is included in the list of what we call 'property word delimiters'. So when an underscore is found, it is treated as a word boundary when building idiomatic java names.

If you want to keep hyphens and spaces as potential word delimiters, you can remove underscores from the list of property word delimiters like this:

`--word-delimiters "- "`

or if you want no word delimiters at all (so no camel-case conversion to make Java field names) then you can use:

`--word-delimiters ""`

**Comment by james-woods** [comment]
Thank you!
