### ISSUE TITLE
Getting OutOfMemoryError for Java heap space when I run Jsonschema2pojo-maven-plugin

### ISSUE THREAD

**Issue by lvimalchandran** [joelittlejohn/jsonschema2pojo#817]
Hi,
I have a json schema (Schema A) which has 10+ entities declared and some of them refers to another schema (Schema B) which is 1.7mb in size and 1000+ entities and each will have 10+ attributes/properties.
I have pointed Schema A in jsonschema2pojo plugin and try to generate pojo classes for all my Schema A entities and also the referred entities from Schema B (hardly 10 entities are referred). 

For the above use case whenever I try to run maven, I am getting OutOfMemoryError for Java Heap space.
I have also tried by setting vm args to 2g for max heap size. but still getting the same error.

Can you please let me know whether jsonschema2pojo will work if the referenced schema has 1000+ entities.

I am using java6 and jsonschema2pojo 0.4.34 version.

Thanks, Vimal.

**Comment by joelittlejohn** [comment]
What else is happening as part of this build? I have never heard of people producing OOM errors with this plugin before. Those do seem like large schemas though. If it is jsonschema2pojo that is running out of memory, I can't easily think of a way to reduce memory usage but lets investigate further.

Could you try running only generate-sources phase, so:
```
mvn generate-sources
```

Does this cause the OOM error? If you can run this step successfully then I think your problem is not in this plugin.

**Comment by lvimalchandran** [comment]
Hi,
Its a simple maven project which has only jsonschema2pojo-maven-plugin and jackson-databind jar.
The goal is to generate and there is no other classes or operation I am doing here.

Please see the below log trace for more information.

[DEBUG] Configuring mojo org.jsonschema2pojo:jsonschema2pojo-maven-plugin:0.4.34:generate from plugin realm ClassRealm[plugin>org.jsonschema2pojo:jsonschema2pojo-maven-plugin:0.4.34, parent: sun.misc.Launcher$AppClassLoader@f4a24a]
[DEBUG] Configuring mojo 'org.jsonschema2pojo:jsonschema2pojo-maven-plugin:0.4.34:generate' with basic configurator -->
[DEBUG]   (f) addCompileSourceRoot = true
[DEBUG]   (f) annotationStyle = jackson2
[DEBUG]   (f) constructorsRequiredPropertiesOnly = false
[DEBUG]   (f) customAnnotator = org.jsonschema2pojo.NoopAnnotator
[DEBUG]   (f) customRuleFactory = org.jsonschema2pojo.rules.RuleFactory
[DEBUG]   (f) fileExtensions = []
[DEBUG]   (f) formatDateTimes = false
[DEBUG]   (f) formatDates = false
[DEBUG]   (f) generateBuilders = false
[DEBUG]   (f) includeAccessors = true
[DEBUG]   (f) includeAdditionalProperties = true
[DEBUG]   (f) includeConstructors = false
[DEBUG]   (f) includeDynamicAccessors = false
[DEBUG]   (f) includeHashcodeAndEquals = true
[DEBUG]   (f) includeJsr303Annotations = false
[DEBUG]   (f) includeToString = true
[DEBUG]   (f) inclusionLevel = NON_NULL
[DEBUG]   (f) initializeCollections = true
[DEBUG]   (f) outputDirectory = C:\workplace\Json2PojoGenerator\target\java-gen
[DEBUG]   (f) outputEncoding = UTF-8
[DEBUG]   (f) parcelable = false
[DEBUG]   (f) project = MavenProject: com.freddiemac.sellingmod:Json2PojoGenerator:0.0.1-SNAPSHOT @ C:\workplace\Json2PojoGenerator\pom.xml
[DEBUG]   (f) propertyWordDelimiters = - _
[DEBUG]   (f) refFragmentPathDelimiters = #/.
[DEBUG]   (f) removeOldOutput = false
[DEBUG]   (f) skip = false
[DEBUG]   (f) sourceDirectory = C:\workplace\Json2PojoGenerator/src/main/resources/JSONSchema_1513704287836.json
[DEBUG]   (f) sourcePaths = []
[DEBUG]   (f) sourceSortOrder = OS
[DEBUG]   (f) sourceType = jsonschema
[DEBUG]   (f) targetPackage = com.freddiemac.vo
[DEBUG]   (f) targetVersion = 1.6
[DEBUG]   (f) useBigDecimals = false
[DEBUG]   (f) useBigIntegers = false
[DEBUG]   (f) useCommonsLang3 = false
[DEBUG]   (f) useDoubleNumbers = true
[DEBUG]   (f) useJodaDates = false
[DEBUG]   (f) useJodaLocalDates = false
[DEBUG]   (f) useJodaLocalTimes = false
[DEBUG]   (f) useLongIntegers = false
[DEBUG]   (f) usePrimitives = false
[DEBUG] -- end configuration --
[DEBUG] Adding project artifact to classpath: C:\workplace\Json2PojoGenerator\target\classes
[DEBUG] Adding project artifact to classpath: C:\m2\repository\commons-lang\commons-lang\2.4\commons-lang-2.4.jar
[DEBUG] Adding project artifact to classpath: C:\m2\repository\com\fasterxml\jackson\core\jackson-databind\2.5.4\jackson-databind-2.5.4.jar
[DEBUG] Adding project artifact to classpath: C:\m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.5.0\jackson-annotations-2.5.0.jar
[DEBUG] Adding project artifact to classpath: C:\m2\repository\com\fasterxml\jackson\core\jackson-core\2.5.4\jackson-core-2.5.4.jar
Dec 20, 2017 9:46:40 AM com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector <clinit>
WARNING: Unable to load JDK7 annotation types; will have to skip
[ERROR] Java heap space -> [Help 1]
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:2834)
	at com.fasterxml.jackson.core.sym.ByteQuadsCanonicalizer._appendLongName(ByteQuadsCanonicalizer.java:954)
	at com.fasterxml.jackson.core.sym.ByteQuadsCanonicalizer.addName(ByteQuadsCanonicalizer.java:850)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.addName(UTF8StreamJsonParser.java:2358)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.findName(UTF8StreamJsonParser.java:2242)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.parseLongName(UTF8StreamJsonParser.java:1840)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.parseMediumName2(UTF8StreamJsonParser.java:1804)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.parseMediumName(UTF8StreamJsonParser.java:1761)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parseName(UTF8StreamJsonParser.java:1696)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextFieldName(UTF8StreamJsonParser.java:1021)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:219)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:224)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:224)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:224)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2401)
	at org.jsonschema2pojo.ContentResolver.resolve(ContentResolver.java:67)
	at org.jsonschema2pojo.SchemaStore.create(SchemaStore.java:50)
	at org.jsonschema2pojo.SchemaStore.create(SchemaStore.java:120)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:59)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:75)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:43)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:70)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:38)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:115)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:66)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:90)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:40)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/OutOfMemoryError

**Comment by lvimalchandran** [comment]
Hi Joe,
One more question. In Json schema I have mentioned items attribute --> items": {"$ref": "#/properties/Child1Container"}  and
type attribute --> "type": "array" for Child1Container property.

In the generated I am able to see List declaration for the "Child1Container" but it didn't mentioned anything for the keyword items in pojo class. because of this when i do schema validation for the json generated using the above pojo with the help of "json-schema-validator". It throws the below schema validation error.

Error Message: instance type (array) does not match any allowed primitive type (allowed: ["object"])

**Comment by lvimalchandran** [comment]
I fixed the above issue by changing attribute name(Child1Container**s**) different from $ref name(Child1Container).
