### ISSUE TITLE
Move to Java 8

### ISSUE THREAD

**Issue by joelittlejohn** [joelittlejohn/jsonschema2pojo#860]

**Comment by ShanthkumarS079** [comment]
Please let me which version of jsonschem2pojo supports the jdk11.
I am getting an error 
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/FilenameUtils
        at org.jsonschema2pojo.Jsonschema2Pojo.getNodeName(Jsonschema2Pojo.java:175)
        at org.jsonschema2pojo.Jsonschema2Pojo.getNodeName(Jsonschema2Pojo.java:170)
        at org.jsonschema2pojo.Jsonschema2Pojo.generateRecursive(Jsonschema2Pojo.java:134)
        at org.jsonschema2pojo.Jsonschema2Pojo.generate(Jsonschema2Pojo.java:75)
        at org.jsonschema2pojo.Jsonschema2Pojo$generate.call(Unknown Source)
        at org.jsonschema2pojo.gradle.GenerateJsonSchemaJavaTask.generate(GenerateJsonSchemaJavaTask.groovy:70)
