### ISSUE TITLE
IllegalArgumentException using resource ref in json schema

### ISSUE THREAD

**Issue by merlin-hst** [joelittlejohn/jsonschema2pojo#898]
I'm not sure if this really is an issue. 

I'm having a maven project with some json schemas organzied into folders like this:

src/main/resources/schema/json/modules/moduleA/typesA.json src/main/resources/schema/json/modules/moduleA/typeA.json

So both schemas are located in the same folder.

The typesA schema links to the typeA schema like this:

` "$ref": "resource:/schema/json/modules/moduleA/typeA.json"`

Because I'd like to generated Java POJOS for all my schemas I'm using the jsonschema2pojo-maven-plugin like this:

```xml
<!-- Code generation out of JsonSchema files -->
<plugin>
    <groupId>org.jsonschema2pojo</groupId>
    <artifactId>jsonschema2pojo-maven-plugin</artifactId>
    <version>0.5.1</version>
    <configuration>
        <skip>false</skip>
        <sourceDirectory>${basedir}/src/main/resources/schema/json/modules/</sourceDirectory>
        <outputDirectory>${basedir}/src/gen/java/json</outputDirectory>
        <removeOldOutput>true</removeOldOutput>
        <annotationStyle>none</annotationStyle>
        <includeGetters>true</includeGetters>
        <includeSetters>true</includeSetters>
        <useCommonsLang3>true</useCommonsLang3>
        <useLongIntegers>true</useLongIntegers>
        <includeJsr303Annotations>true</includeJsr303Annotations>
        <includeAdditionalProperties>false</includeAdditionalProperties>
        <includeHashcodeAndEquals>false</includeHashcodeAndEquals>
        <dateTimeType>java.time.LocalDateTime</dateTimeType>
        <targetPackage>com.all.my.modules</targetPackage>
    </configuration>
    <executions>
       <execution>
            <phase>generate-sources</phase>
            <goals>
               <goal>generate</goal>
            </goals>
       </execution>
    </executions>
</plugin>
```

But when I run "mvn clean compile" it always fails with the following stacktrace:

Caused by: java.lang.IllegalArgumentException: Couldn't read content from the classpath, file not found: resource:/schema/json/modules/moduleA/typeA.json at org.jsonschema2pojo.ContentResolver.resolveFromClasspath(ContentResolver.java:94) at org.jsonschema2pojo.ContentResolver.resolve(ContentResolver.java:73) at org.jsonschema2pojo.SchemaStore.create(SchemaStore.java:58) at org.jsonschema2pojo.SchemaStore.create(SchemaStore.java:128) at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:59) at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30) at org.jsonschema2pojo.rules.ArrayRule.apply(ArrayRule.java:81) at org.jsonschema2pojo.rules.ArrayRule.apply(ArrayRule.java:37) at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:113) at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:40) at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73) at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30) at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:75) at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:43) at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:70) at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:38) at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:119) at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:70) at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:90) at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:40) at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73) at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:66) at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30) at org.jsonschema2pojo.SchemaMapper.generate(SchemaMapper.java:92) at org.jsonschema2pojo.Jsonschema2Pojo.generateRecursive(Jsonschema2Pojo.java:134) at org.jsonschema2pojo.Jsonschema2Pojo.generateRecursive(Jsonschema2Pojo.java:136) at org.jsonschema2pojo.Jsonschema2Pojo.generateRecursive(Jsonschema2Pojo.java:136) at org.jsonschema2pojo.Jsonschema2Pojo.generateRecursive(Jsonschema2Pojo.java:136) at org.jsonschema2pojo.Jsonschema2Pojo.generateRecursive(Jsonschema2Pojo.java:136) at org.jsonschema2pojo.Jsonschema2Pojo.generate(Jsonschema2Pojo.java:75) at org.jsonschema2pojo.maven.Jsonschema2PojoMojo.execute(Jsonschema2PojoMojo.java:788) at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132) ... 20 more

But according to [classpathRefs.json ](https://github.com/joelittlejohn/jsonschema2pojo/blob/jsonschema2pojo-0.5.1/jsonschema2pojo-integration-tests/src/test/resources/schema/ref/classpathRefs.json) and [jsonschema2pojo#ref](https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#ref) it should be possible. When I try to debug the plugin execution by running mvnDebug sometimes it works and sometimes not. So is this a know problem ? Using only

`"$ref": "typeA.json"`

it works always. But this is only a temporary workaround for me.
See also my question at [stackoverflow](https://stackoverflow.com/questions/51824071/illegalargumentexception-using-resource-ref-in-json-schema).

Java 8 + maven 3.2.5

**Comment by joelittlejohn** [comment]
Strange, it seems like the schemas are sometimes not on the classpath. Is it possible that it works if you don't `mvn clean` and it fails when you using `mvn clean` before the build?

**Comment by merlin-hst** [comment]
You're right. Using only `mvn compile` it seems to work. But from my point of view everything under `resources` should always be available in the classpath.

**Comment by joelittlejohn** [comment]
By default this plugin binds to the `generate-sources` phase. I don't think resources in the current module will be available on the classpath at this time.

You could try moving the execution of this plugin into a later phase. As long as it happens before the `compile` phase then your build should still work correctly. I think you probably need `process-resources` to have occurred:

http://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html

I can't remember whether the plugins you bind in your own pom.xml will be run after the other default plugins have executed or before. Basically though, I think you should bind jsonschema2pojo to either the `compile` or `process-resources` phase to fix this problem.

**Comment by joelittlejohn** [comment]
Yes, `resource:` and `classpath:` read from the classpath.

**Comment by joelittlejohn** [comment]
I've added a note to the docs.

**Comment by merlin-hst** [comment]
I know that I can use `classpath `and `resource `inside a JSON schema to include another schema. But as I understand the jsonschema2pojo maven plugin  always tries to resolve the properties sourceDirectory and sourcePaths against the filesystem. At least when I try to use for example `classpath:/resources/schema/json` I'm getting an exception saying "unkown protocol".

**Comment by joelittlejohn** [comment]
Ah, I see what you mean. You want to _start_ the entire process with a classpath ref.

I think the only way to achieve this would be to create a single schema on the file system that has a "$ref" inside it, like:

```json
{
"$ref":"classpath:/...."
}
```

**Comment by merlin-hst** [comment]
Works great. But now I'm having the situation that the POJOS are not generated because the dependency with the schemas is (and must be) available in the classpath. Unfortunately these dependency contains classes with the same name and package as the classes I want to generate.  So is there a way to "force" generation of the POJOS ? Adding a prefix by using `classNamePrefix` doesn't help.

**Comment by joelittlejohn** [comment]
So I take it this means you are using the `javaType` keyword?

Which version of jsonschema2pojo are you using? 

In 1.0.0 (most recent release is 1.0.0-alpha4) we make 'reuse' vs 'regenerate' explicit by splitting javaType into two different rules: `javaType` and `existingJavaType`. If you want to generate a new type and give it a specific FQN, you use the former. If you want to refer to existing types on the classpath and skip generation then you use the latter. The goal here is to avoid problems like the one you have now (and ensure that types are regenerated on every build, even if you don't `mvn clean` to clear out any previously generated types that have been compiled).

So, I _think_ using 1.0.0-alpha4 will solve your problem. For more info on this, see #828. Also for more info on breaking changes that are in the 1.0.0 release see [the changelog](https://github.com/joelittlejohn/jsonschema2pojo/blob/master/CHANGELOG.md).

**Comment by merlin-hst** [comment]
OK. Do you have an idea when version 1.0.0 might be available ?

**Comment by joelittlejohn** [comment]
1.0.0-alpha4 is available right now. No idea when 1.0.0 will drop.
