### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: Path not present: org

### ISSUE THREAD

**Issue by bnofer** [joelittlejohn/jsonschema2pojo#939]
Issuing this command:
./jsonschema2pojo --source OTA_AirLowFareSearchRQ.jsonschema --target /src-gen --source-type JSONSCHEMA --target-language JAVA --annotation-style JACKSON2 --include-dynamic-getters --include-dynamic-setters --enable-additional-properties

Getting the following out put:
readlink: illegal option -- f
usage: readlink [-n] [file ...]
Exception in thread "main" java.lang.IllegalArgumentException: Path not present: org
	at org.jsonschema2pojo.FragmentResolver.resolve(FragmentResolver.java:54)
	at org.jsonschema2pojo.FragmentResolver.resolve(FragmentResolver.java:52)
	at org.jsonschema2pojo.FragmentResolver.resolve(FragmentResolver.java:31)
	at org.jsonschema2pojo.SchemaStore.create(SchemaStore.java:63)
	at org.jsonschema2pojo.SchemaStore.create(SchemaStore.java:132)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:69)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:38)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:64)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:34)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:70)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:38)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:123)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:74)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:92)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:40)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:85)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:38)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:64)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:34)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:70)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:38)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:123)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:74)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:92)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:40)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:85)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:76)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:38)
	at org.jsonschema2pojo.SchemaMapper.generate(SchemaMapper.java:92)
	at org.jsonschema2pojo.Jsonschema2Pojo.generate(Jsonschema2Pojo.java:77)
	at org.jsonschema2pojo.cli.Jsonschema2PojoCLI.main(Jsonschema2PojoCLI.java:52)

Please advise

**Comment by joelittlejohn** [comment]
Do you have a `$ref` value that points to a file that doesn't exist? Maybe the ref includes a `#`?

**Comment by bnofer** [comment]
Perhaps I could share the schema with you and it might be easier to figure out the issue.  Could we discuss offline?

**Comment by joelittlejohn** [comment]
Sure, send to my github username at gmail.com if you want.

**Comment by joelittlejohn** [comment]
By default jsonschema2pojo supports two different ways of declaring fragments, JSONPath and JSON Pointer. This means we support both `/` and `.` as separating path elements. So a ref that looks like:

```
#/definitions/org.foo.ota._2003._05.Bar
```

Is expected to be available at:
```json
{"definitions":{"org":{"foo":{"ota":{"_2003":{"_05":{"Bar":{...}}}}}}}}
```

This behaviour is configurable though, using the config property `<refFragmentPathDelimiters>`. By default it is set to `#/.`, but you can set it to `#/` and it will no longer treat `.` like a delimiter.

**Comment by joelittlejohn** [comment]
Given that JSON Pointer has won, and the JSON Schema specification now explicitly references JSON Pointer, I think we should remove `.` from the path delimiters in jsonschema2pojo 1.0.0. If people want to continue to use JSONPath, they can add `.` as to refFragmentPathDelimiters.

**Comment by bnofer** [comment]
That definitely helped.  Thank you
